### ISSUE TITLE
Binaries

### ISSUE THREAD

**Issue by BenVlodgi** [JanSeliv/PoolManager#5]
Binaries shouldn't be pushed with the git repo, because:
- Each version of them will be stored in-whole in the repository. They aren't stored as diff deltas like text files, and are bloating the project size and pull time.
- Binaries built for your project aren't compatible with other projects unless you used the plugin build tool to generate them

To clean up the repo, you can purge the binaries from the history, and add that folder to the `.gitignore`.
To share binaries for people who don't know how to build UE Plugins, you can attach them to [Releases](https://github.com/JanSeliv/PoolManager/releases) as you have been.

**Comment by JanSeliv** [comment]
Thanks for your feedback.

I upload binaries because I support only a specific version of Unreal Engine per plugin release, usually the last officially released version. I don't support a range of engine versions.

Regarding your concerns:

- **Size**: This is not a big deal since I update binaries only once per release. If someone's struggling with size, the Release page is way to download then, where I keep uploading every plugin release.
  
- **Compatibility**: I compile the binaries using the plugin build tool specifically for the Development UE configuration. This ensures compatibility with other projects as long as they use the last version from the launcher of the Unreal Engine supported by this plugin's Main branch. Our team is currently using these binaries on their UE5.4 on blueprints-only project without any recompile issues.
  
Uploading binaries is very important for content developers for the following reasons:

- This plugin might be used as a submodule in different projects where only blueprint developers work. It's crucial to have ready-to-go binaries for them since they are not able to recompile it by themselves.
  
- Finally, it’s more convenient for blueprint developers, who often prefer to download the Main branch directly instead of navigating to the release page.

If you struggle with binaries on your project, you can simply configure your git to ignore them inside the project:

```
git ls-files -- *.target | xargs -l git update-index --assume-unchanged
git ls-files -- *.modules | xargs -l git update-index --assume-unchanged
git ls-files -- *.dll | xargs -l git update-index --assume-unchanged
git ls-files -- *.pdb | xargs -l git update-index --assume-unchanged
```

Alternatively, you can just put this plugin under Engine directory, where all plugins from marketplace are located, so your project will not try to recompile them.

Closing the issue

**Comment by BenVlodgi** [comment]
I appreciate the thoughtful explanation.
I understand the utility in your current approach.

Most developers who come to GitHub for plugins _are_ compiling them themselves... those who aren't can be directed to use the releases. This is the expected workflow for GitHub in general, and all other UE plugins I've used.

If you want binaries to be stored with your project, you can use [git-lfs](https://git-lfs.com/). If you don't want to use lfs, then you can also create a separate repository for just the binaries for those who want to import that as a submodule with prebuild binaries.

Thank you for the commands to filter away these files, for ongoing development it'd be fine. My initial pull takes many minutes.
The current repository size is `588.7 MB`.
Without binaries and their history, the current repository size is `0.1 MB`.
